defmodule CanopyWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :canopy

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_canopy_key",
    signing_salt: "IQy96l1A",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Terminal channel socket — separate from the LiveView socket so we don't
  # pollute the live socket namespace. Frontend points to /socket/websocket.
  socket "/socket", CanopyWeb.UserSocket, websocket: true, longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :canopy,
    gzip: not code_reloading?,
    only: CanopyWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :canopy
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # CORS — installed at the endpoint so OPTIONS preflight requests are handled
  # before they hit the router (which only matches concrete method+path pairs).
  # Origins are configured in config/dev.exs via :canopy, :cors_origins.
  plug Corsica,
    origins: Application.compile_env(:canopy, :cors_origins, []),
    allow_credentials: true,
    allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    allow_headers: ["content-type", "authorization", "x-requested-with"],
    max_age: 86_400

  plug CanopyWeb.Router
end
