import Config

# Local PostgreSQL — using system user (no password on local socket)
config :canopy, Canopy.Repo,
  username: System.get_env("PGUSER") || "rhl",
  password: System.get_env("PGPASSWORD") || "",
  hostname: "localhost",
  database: "canopy_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Dev endpoint — port 9190 (shifted from 9090 to avoid collisions with other local services)
config :canopy, CanopyWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 9190],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "iNL7tyd7LXRU922XhmurVZVy9IjT7zYk6KK0RyrVx5lQifs9owL1VWkM7JNgL/uM",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :canopy, dev_routes: true

# CORS origins for dev mode.
# Tauri native app talks over ipc:// and does NOT trigger CORS preflight.
# This is only needed when running the desktop in a browser (vite dev at :5280).
config :canopy, :cors_origins, [
  "http://localhost:5280",
  "http://127.0.0.1:5280",
  "tauri://localhost",
  "http://tauri.localhost"
]

# MIOSA compute API — set real values in .env for local dev with sandbox support.
# When not set, Canopy.Miosa.configured?() returns false and sandbox provisioning
# is skipped gracefully (miosa_sandbox_status: "skipped").
config :canopy, :miosa_api_url, System.get_env("MIOSA_API_URL", "")
config :canopy, :miosa_api_key, System.get_env("MIOSA_API_KEY", "")

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
